### PR TITLE
Supply apple-touch-icon.{svg,png} for supported Distributions

### PR DESCRIPTION
**Pull request by lkocman**
Supply apple-touch-icon.{svg,png} for Leap, LeapMicro, Tumbleweed, MicroOS and Aeon

* Present in SLES 15
* Cockpit utilizes these icons
*  It's the last missing piece to be able to re-run cockpit build in SLE/Micro on Leap/LeapMicro
* Related to https://github.com/openSUSE/branding/pull/147

### CODE REVIEW

**Comment by hellcp** [comment]
Do we need those circles? they don't fit there very well

**Comment by lkocman** [comment]
@hellcp it seems to be the purpose of these icons. The sles one looks like this ... well actually it seems to have white filling, which I missed. Not sure if that is good or not.

apple-touch-icon

**Comment by lkocman** [comment]
I do like the blend of TW logo with the circle. The rest looks somehow more religious than before.

**Comment by hellcp** [comment]
That seems really ugly, can we use like a rounded rectangle instead without a border? We could even fill it with branding color and make the icons white or black

**Comment by lkocman** [comment]
Roger that @hellcp. I'll rework them. Btw I'll use white bg to match SLES

**Comment by lkocman** [comment]
apple-touch-icon
apple-touch-icon
apple-touch-icon
apple-touch-icon
apple-touch-icon

**Comment by lkocman** [comment]
@hellcp hope you like it. I did skip Kubic for obvious reasons :-)

**Pull request merged**
